### ISSUE TITLE
TypeError while running script

### ISSUE THREAD

**Issue by XanderStoffels-KDG** [kevhauma/MessengertoStats#1]
While running `node script.js` I encountered the following error:

`TypeError:Cannot read property 'split' of undefined    at ` `C:\Users\xande\Documents\Projects\MessengerToStats\script.js:101:40   at FSReqWrap.readFileAfterClose ` `[asoncomplete] (fs.js:511:3)` 

I provided input files in the input folder. 
No output files have been created.

**Comment by kevhauma** [comment]
fixed

**Comment by XanderStoffels** [comment]
Still have the same problem as of commit #a7f7e72

**Comment by Jd3vil** [comment]
Also have that same issue

Date in my HTML file is written as follow:

Monday, April 16, 2018 at 10:33am EDT
Monday, February 12, 2018 at 11:12pm EST

In your file, it was written as follow:

Thursday, 1 February 2018 at 21:56 UTC+01

Do you think you can adapt your code so it works with my format? I tried to play with the code but didn't manage it
Thank you

**Comment by kevhauma** [comment]
Oh yeah, I can see the issue now. 

Fill release fix later this day.

**Comment by kevhauma** [comment]
now will work with formats:
-Monday, 12 February 2018 at 23:12 UTC+01
-Monday, February 12, 2018 at 11:12pm EST
