### ISSUE TITLE
Doesn't Seem to be working?

### ISSUE THREAD

**Issue by pachicola** [kevhauma/MessengertoStats#5]
I'm pretty sure I have everything set up right, I run the install.bat, put the html file into the input folder, then when I run the Run.bat nothing happens. The console flashes up, but nothing ends up in the output folder. With either my own html, or the example html. I'm not sure if there are any steps I'm supposed to do beforehand.

**Comment by XanderStoffels** [comment]
Do you have Node.js installed?

**Comment by kevhauma** [comment]
Node.js should be installed. And the download folder should have read and read rights

**Comment by pachicola** [comment]
Fixed! Thanks guys
