### ISSUE TITLE
Export Data is cluttered

### ISSUE THREAD

**Issue by trptfunk** [kevhauma/MessengertoStats#7]
Hi there,

Got everything to export put when comparing my csv file to your image preview mine is much different. Your's is all neat and mine is really quite jumbled. I can make out certain things but I'm not sure what I did wrong. I opened it in Excel.
![capture](https://user-images.githubusercontent.com/39684220/40593642-0b7a8634-61e7-11e8-96b0-775032227fe8.JPG)

**Comment by kevhauma** [comment]
For any one else,  change excels seperator to ; 
 

https://support.office.com/en-us/article/change-the-character-used-to-separate-thousands-or-decimals-c093b545-71cb-4903-b205-aebb9837bd1e
